[package]
name = "instagram-agent-n8n"
version = "0.2.1"
description = "Local Instagram n8n executor"
authors = ["Nikita Zigangirov"]
edition = "2021"

[lib]
name = "instagram_agent_n8n_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
